# Generated by Django 4.0 on 2021-12-12 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config_Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_pomodoro', models.PositiveIntegerField()),
                ('time_short_break', models.PositiveIntegerField()),
                ('time_long_break', models.PositiveIntegerField()),
                ('quantity_long_break', models.PositiveIntegerField()),
                ('type_sound', models.CharField(max_length=200)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
