# Generated by Django 4.0 on 2021-12-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_perfil',
            name='quantity_long_break',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='config_perfil',
            name='time_long_break',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='config_perfil',
            name='time_pomodoro',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='config_perfil',
            name='time_short_break',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='config_perfil',
            name='type_sound',
            field=models.CharField(default='digital', max_length=200),
        ),
    ]
