# Generated by Django 4.0 on 2022-01-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0002_alter_config_perfil_quantity_long_break_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config_perfil',
            name='teste',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
